spring:
  application:
    name: api-gateway

  #jwt validation
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ENDPOINT}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      #configure routes
      routes:
        - id: PROBLEM-SERVICE
          uri:
            lb://PROBLEM-SERVICE
          predicates:
            - Path=/api/problems/**
        - id: USER_SERVICE
          uri:
            lb://USER_SERVICE
          predicates:
            - Path=/api/user/**





#enable eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



#port
server:
  port: 9000
