spring:
  application:
    name: api-gateway

  #jwt validation
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ENDPOINT}

  #gateway
  cloud:
    gateway:
      discovery:

        locator:
          enabled: true
      #configure routes
      routes:
        - id: problem-service
          uri:
            lb://problem-service
          predicates:
            - Path=/api/problems/**
        - id: user-service
          uri:
            lb://user-service
          predicates:
            - Path=/api/user/**
        - id: code-runner-service
          uri:
            lb://code-runner-service
          predicates:
            - Path=/api/code-runner/**


    #consul client
    consul:
      port: 8500
      host: localhost
      discovery:
        instance-id: ${spring.application.name}-${server.port}
        register: true


#port
server:
  port: 9000

#health check
management:
  endpoints:
    web:
      exposure:
        include: health,info

#key
admin:
  key: ${APP_API_KEY}
  service:
    key: ${ADMIN_SERVICE_KEY}