spring:
  application:
    name: user-service

  #db config
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #check jwt token from clerk
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ENDPOINT}


  #consul client
  cloud:
    consul:
      discovery:
        register: true
        instance-id: ${spring.application.name}-${server.port}
        prefer-ip-address: true
      host: localhost
      port: 8500

server:
  port: 8081

#token
CLERK_TOKEN: ${CLERK_TOKEN}

