spring:
  application:
    name: problem-service



  #database config
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  #consul client
  cloud:
    consul:
      discovery:
        register: true
        instance-id: ${spring.application.name}-${server.port}
        prefer-ip-address: true
      host: localhost
      port: 8500


  #ddl
  jpa:
    hibernate:
      ddl-auto: update

#port
server:
  port: 8082

#s3 bucket
supabase:
  url: ${S3_URL}
  service-key: ${S3_ACCESS_KEY}
  bucket: ${S3_BUCKET}

#health check
management:
  endpoints:
    web:
      exposure:
        include: health,info

