spring:
  application:
    name: code-runner-service
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        register: true
        instance-id: ${spring.application.name}-${server.port}
        prefer-ip-address: true

#port
server:
  port: 8083

#consul client

#health check
management:
  endpoints:
    web:
      exposure:
        include: health, info