spring:
  application:
    name: code-runner-service

#port
server:
  port: 8083

#eureka server configure
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
